# Uncomment this line to define a global platform for your project
# platform :ios, ‘9.0’
use_frameworks!

target 'Fresh' do
pod ‘Parse’
#pod 'Reveal-iOS-SDK', :configurations => ['Debug']
end

target 'FreshTests' do

end

target 'FreshUITests' do

end

