# Uncomment this line to define a global platform for your project
# platform :ios, ‘8.3’
use_frameworks!

target 'Fresh' do
pod ‘Parse’
end

target 'FreshTests' do

end

target 'FreshUITests' do

end

